# Generated by Django 3.2.4 on 2021-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todopedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPedido', models.IntegerField(unique=True, verbose_name='Número de pedido')),
                ('pedido', models.CharField(max_length=20, verbose_name='Pedido')),
                ('descri', models.CharField(max_length=20, verbose_name='Descripción')),
                ('client', models.CharField(max_length=20, verbose_name='Cliente')),
                ('fechadEnt', models.CharField(blank=True, max_length=100, verbose_name='Fecha de entrega')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id'],
            },
        ),
    ]
