# Generated by Django 3.2.4 on 2021-08-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todopedido',
            name='estado',
            field=models.CharField(default='', max_length=20, verbose_name='Estado'),
        ),
    ]
