# Generated by Django 3.2.4 on 2021-08-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_todopedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todopedido',
            name='numPedido',
        ),
    ]
