# Generated by Django 3.2.4 on 2021-08-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_todopedido_numpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todopedido',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado'),
        ),
    ]
