# Generated by Django 3.2.4 on 2021-08-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regusu',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='Aceptar términos y condiciones'),
        ),
    ]
