# Generated by Django 3.2.4 on 2021-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsRegInsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_insumo', models.CharField(choices=[('select_tip', 'Seleccione un tipo de insumo'), ('tela', 'Telas'), ('hilo', 'Hilos y lanas'), ('adorno', 'Adorno y bisutería'), ('accesorio', 'Accesorios, cintas y complementos'), ('herramienta', 'Herramientas e instrumentos'), ('otros', 'Otros')], default='Sel-tip-ins', max_length=30)),
                ('especificacion_insumo', models.TextField(max_length=1500, verbose_name='Tipo, marca y otros')),
                ('estado_insumo', models.CharField(max_length=30, verbose_name='Cantidad o estado')),
                ('costxunid_insumo_costo', models.PositiveIntegerField(default=0)),
                ('costxunid_insumo_unidad', models.CharField(max_length=20, verbose_name='cm, kilos, unidades, etc')),
            ],
            options={
                'verbose_name': 'Registro insumo',
                'verbose_name_plural': 'Registro insumos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InsRegProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100, verbose_name='Establecimiento/persona')),
                ('Insumos_proveedor', models.TextField(max_length=2000, verbose_name='Insumos que vende')),
                ('telefono_proveedor', models.IntegerField(default=0, unique=True)),
                ('correo_proveedor', models.EmailField(max_length=50, unique=True, verbose_name='E-mail proveedor')),
                ('ubicacion_proveedor', models.CharField(max_length=50, verbose_name='Dirección de proveedor')),
                ('rel_ProvInsu', models.ManyToManyField(to='insumos.InsRegInsu')),
            ],
            options={
                'verbose_name': 'Registro proveedor',
                'verbose_name_plural': 'Registro proveedores',
                'ordering': ['id'],
            },
        ),
    ]
