# Generated by Django 3.2.4 on 2021-08-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsRegInsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_insumo', models.CharField(choices=[('', 'Seleccione un tipo de insumo'), ('Tela', 'Telas'), ('Hilos/lanas/cordones', 'Hilos, lanas, cordones'), ('Adorno/Bisuteria', 'Adorno y bisutería'), ('Accesorios/Complementos', 'Accesorios, cintas y complementos'), ('Herramienta/instrumento', 'Herramientas e instrumentos'), ('Otros', 'Otros')], default='', max_length=30, verbose_name='Sel    eccione un tipo de insumo')),
                ('especificacion_insumo', models.TextField(max_length=100, verbose_name='Tipo, marca y otros')),
                ('estado_insumo', models.CharField(max_length=30, verbose_name='Cantidad o estado')),
                ('costxunid_insumo_costo', models.PositiveIntegerField(default=0, verbose_name='Costo insumo')),
                ('costxunid_insumo_unidad', models.CharField(max_length=20, verbose_name='Cm, kilos, unidades, etc')),
            ],
            options={
                'verbose_name': 'Registro insumo',
                'verbose_name_plural': 'Registro insumos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InsRegProv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=60, verbose_name='Establecimiento/persona')),
                ('Insumos_proveedor', models.TextField(max_length=222, verbose_name='Insumos que vende')),
                ('telefono_proveedor', models.IntegerField(unique=True, verbose_name='Teléfono proveedor')),
                ('correo_proveedor', models.EmailField(max_length=50, unique=True, verbose_name='E-mail proveedor')),
                ('ubicacion_proveedor', models.CharField(max_length=50, verbose_name='Dirección de proveedor')),
            ],
            options={
                'verbose_name': 'Registro proveedor',
                'verbose_name_plural': 'Registro proveedores',
                'ordering': ['id'],
            },
        ),
    ]
