# Generated by Django 3.2.4 on 2021-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insregprov',
            name='rel_ProvInsu',
        ),
        migrations.AlterField(
            model_name='insreginsu',
            name='costxunid_insumo_costo',
            field=models.PositiveIntegerField(default=0, verbose_name='Costo insumo'),
        ),
        migrations.AlterField(
            model_name='insreginsu',
            name='costxunid_insumo_unidad',
            field=models.CharField(max_length=20, verbose_name='Cm, kilos, unidades, etc'),
        ),
        migrations.AlterField(
            model_name='insreginsu',
            name='especificacion_insumo',
            field=models.TextField(max_length=100, verbose_name='Tipo, marca y otros'),
        ),
        migrations.AlterField(
            model_name='insreginsu',
            name='tipo_insumo',
            field=models.CharField(choices=[('', 'Seleccione un tipo de insumo'), ('Tela', 'Telas'), ('Hilos/lanas/cordones', 'Hilos, lanas, cordones'), ('Adorno/Bisuteria', 'Adorno y bisutería'), ('Accesorios/Complementos', 'Accesorios, cintas y complementos'), ('Herramienta/instrumento', 'Herramientas e instrumentos'), ('Otros', 'Otros')], default='', max_length=30, verbose_name='Sel    eccione un tipo de insumo'),
        ),
        migrations.AlterField(
            model_name='insregprov',
            name='Insumos_proveedor',
            field=models.TextField(max_length=222, verbose_name='Insumos que vende'),
        ),
        migrations.AlterField(
            model_name='insregprov',
            name='nombre_proveedor',
            field=models.CharField(max_length=60, verbose_name='Establecimiento/persona'),
        ),
        migrations.AlterField(
            model_name='insregprov',
            name='telefono_proveedor',
            field=models.IntegerField(unique=True, verbose_name='Teléfono proveedor'),
        ),
    ]
