# Generated by Django 3.2.4 on 2021-08-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo_usu', models.EmailField(max_length=50, unique=True, verbose_name='E-mail de contacto')),
                ('cont_asunto', models.CharField(max_length=500, verbose_name='Asunto')),
                ('cont_mensaje', models.TextField(max_length=2000, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Usuario en contacto',
                'verbose_name_plural': 'Usuarios en contacto',
                'ordering': ['id'],
            },
        ),
    ]
