# Generated by Django 3.2.4 on 2021-08-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCli', models.CharField(max_length=50, unique=True, verbose_name='Nombre cliente')),
                ('apeCli', models.CharField(max_length=50, unique=True, verbose_name='Apellido cliente')),
                ('telCli', models.IntegerField(default=0, unique=True, verbose_name='Teléfono cliente')),
                ('celCli', models.IntegerField(default=0, unique=True, verbose_name='celular cliente')),
                ('e_mailCli', models.EmailField(max_length=254, unique=True, verbose_name='E-mail cliente')),
                ('dirCli', models.CharField(max_length=50, verbose_name='Dirección de cliente')),
                ('imgCli', models.ImageField(blank=True, null=True, upload_to='Fotos-Clientes')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InfoGeneClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoTCli', models.TextField(max_length=3000, verbose_name='Info técnica cliente')),
                ('ver_ITC', models.CharField(blank=True, max_length=200, null=True, verbose_name='verificación realizada')),
                ('revP_ITC', models.CharField(blank=True, max_length=200, null=True, verbose_name='Revisar pronto')),
                ('revIM_ITC', models.CharField(blank=True, max_length=200, null=True, verbose_name='Revisar de inmediato')),
                ('tipoCli', models.CharField(choices=[('cliente local', 'cliente local'), ('cliente nacional', 'cliente nacional')], default='cliente local', max_length=100)),
                ('prenda', models.BooleanField(null=True, verbose_name='tipos de prenda')),
                ('estilCli', models.CharField(choices=[('clasico', 'clasico'), ('deportivo', 'deportivo'), ('moderno', 'moderno'), ('oficio', 'oficio'), ('otro', 'otro'), ('ninguno', 'ninguno')], default='ninguno', max_length=100)),
                ('medPag', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Giro', 'Giro')], default='Efectivo', max_length=100)),
            ],
            options={
                'verbose_name': 'Detalle Cliente',
                'verbose_name_plural': 'Detalles Clientes',
                'ordering': ['id'],
            },
        ),
    ]
