# Generated by Django 3.2.4 on 2021-08-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoclient',
            name='celCli',
            field=models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='celular cliente'),
        ),
        migrations.AlterField(
            model_name='infoclient',
            name='imgCli',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos-Clientes', verbose_name='Imagen del cliente'),
        ),
        migrations.AlterField(
            model_name='infoclient',
            name='telCli',
            field=models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='Teléfono cliente'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='estilCli',
            field=models.CharField(choices=[('clasico', 'clasico'), ('deportivo', 'deportivo'), ('moderno', 'moderno'), ('oficio', 'oficio'), ('otro', 'otro'), ('ninguno', 'ninguno')], default='ninguno', max_length=100, verbose_name='Estilo del cliente'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='infoTCli',
            field=models.TextField(max_length=3000, verbose_name='Información técnica del cliente'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='medPag',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Giro', 'Giro')], default='Efectivo', max_length=100, verbose_name='Medio de pago habitual'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='prenda',
            field=models.BooleanField(null=True, verbose_name='Tipos de prenda'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='revIM_ITC',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota Revisar de inmediato'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='revP_ITC',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota Revisar pronto'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='tipoCli',
            field=models.CharField(choices=[('cliente local', 'cliente local'), ('cliente nacional', 'cliente nacional')], default='cliente local', max_length=100, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='ver_ITC',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota de Verificación realizada'),
        ),
    ]
