# Generated by Django 3.2.4 on 2021-08-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210808_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoclient',
            name='imgCli',
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='prenda',
            field=models.BooleanField(choices=[('vestido', 'vestido'), ('pantalón', 'pantalón'), ('chaqueta', 'chaquetao'), ('Blusa/Camisa', 'Blusa/Camisa')], null=True, verbose_name='Tipos de prenda'),
        ),
    ]
