# Generated by Django 3.2.4 on 2021-08-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20210811_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoclient',
            name='celCli',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='celular cliente'),
        ),
        migrations.AlterField(
            model_name='infoclient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infoclient',
            name='telCli',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Teléfono cliente'),
        ),
    ]
