# Generated by Django 3.2.4 on 2021-08-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20210811_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoclient',
            name='apeCli',
            field=models.CharField(max_length=50, verbose_name='Apellido cliente'),
        ),
        migrations.AlterField(
            model_name='infoclient',
            name='celCli',
            field=models.PositiveIntegerField(default=0, verbose_name='celular cliente'),
        ),
        migrations.AlterField(
            model_name='infoclient',
            name='nomCli',
            field=models.CharField(max_length=50, verbose_name='Nombre cliente'),
        ),
        migrations.AlterField(
            model_name='infoclient',
            name='telCli',
            field=models.PositiveIntegerField(default=0, verbose_name='Teléfono cliente'),
        ),
    ]
