# Generated by Django 3.2.4 on 2021-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20210811_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogeneclient',
            name='estilCli',
            field=models.CharField(choices=[('Clasico', 'Clasico'), ('Deportivo', 'Deportivo'), ('Moderno', 'Moderno'), ('Oficio', 'Oficio'), ('Otro', 'Otro'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=100, verbose_name='Estilo del cliente'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='prenda',
            field=models.BooleanField(choices=[('Vestido', 'Vestido'), ('Pantalón', 'Pantalón'), ('Chaqueta', 'Chaqueta'), ('Blusa/Camisa', 'Blusa/Camisa')], default='Vestido', null=True, verbose_name='Tipos de prenda'),
        ),
        migrations.AlterField(
            model_name='infogeneclient',
            name='tipoCli',
            field=models.CharField(choices=[('Cliente local', 'Cliente local'), ('Cliente nacional', 'Cliente nacional')], default='Cliente local', max_length=100, verbose_name='Tipo de cliente'),
        ),
    ]
