# Generated by Django 3.2.4 on 2021-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20210812_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogeneclient',
            name='prenda',
            field=models.CharField(choices=[('Vestido', 'Vestido'), ('Pantalón', 'Pantalón'), ('Chaqueta', 'Chaqueta'), ('Blusa/Camisa', 'Blusa/Camisa')], default='Vestido', max_length=100, verbose_name='Tipos de prenda'),
        ),
    ]
