# Generated by Django 3.2.4 on 2021-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactar_desarrolladores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(verbose_name='Nombre de usuario')),
                ('user_email', models.TextField(verbose_name='Correo electronico')),
                ('affair', models.TextField(verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'contactar desarrolladores',
                'db_table': 'Contactar Desarrolladores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='editar_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(verbose_name='Nombre de usuario')),
                ('user_email', models.TextField(verbose_name='Correo electronico')),
                ('user_password', models.TextField(verbose_name='Contraseña')),
                ('user_password2', models.TextField(verbose_name='Confirmar contraseña')),
                ('security_question', models.TextField(verbose_name='Pregunta de seguridad')),
                ('answer', models.TextField(verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'editar usuario',
                'db_table': 'Editar Usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='informacion_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(verbose_name='Nombre de usuario')),
                ('user_email', models.TextField(verbose_name='Correo electronico')),
                ('register_joined', models.DateField(auto_now=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'informacion personal',
                'db_table': 'Informacion Personal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='reportar_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(verbose_name='Nombre de usuario')),
                ('user_email', models.TextField(verbose_name='Correo electronico')),
                ('type_error', models.TextField(verbose_name='Tipo de error')),
                ('details_error', models.TextField(verbose_name='Detalles del error')),
            ],
            options={
                'verbose_name': 'reportar error',
                'db_table': 'Reportar Error',
                'ordering': ['id'],
            },
        ),
    ]
