# Generated by Django 3.2.4 on 2021-08-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombCli', models.CharField(max_length=50, verbose_name='Nombre cliente')),
                ('fecharec', models.CharField(max_length=100, verbose_name='Fecha de recibo')),
                ('tipoped', models.CharField(choices=[('Prenda(s)', 'Prenda(s)'), ('Colección', 'Colección'), ('Modificación', 'Modificación'), ('Reparación', 'Reparación')], max_length=100, unique=True, verbose_name='Tipo de pedido')),
                ('fechaLiEn', models.CharField(blank=True, max_length=100, verbose_name='Fecha de limite de entrega')),
                ('lugarEntr', models.CharField(max_length=200, verbose_name='Lugar de entrega')),
                ('medentr', models.CharField(choices=[('Correo', 'Correo'), ('Fábrica o local', 'Fábrica o local'), ('Acordar punto y hora', 'Acordar punto y hora')], max_length=100, unique=True, verbose_name='Medio de entrega')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronograma',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InfoClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomCli', models.CharField(max_length=50, verbose_name='Nombre cliente')),
                ('apeCli', models.CharField(max_length=50, verbose_name='Apellido cliente')),
                ('telCli', models.PositiveIntegerField(default=0, verbose_name='Teléfono cliente')),
                ('celCli', models.PositiveIntegerField(default=0, verbose_name='celular cliente')),
                ('e_mailCli', models.EmailField(max_length=254, unique=True, verbose_name='E-mail cliente')),
                ('dirCli', models.CharField(max_length=50, verbose_name='Dirección de cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InfoGeneClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoTCli', models.TextField(max_length=3000, verbose_name='Información técnica del cliente')),
                ('ver_ITC', models.CharField(max_length=200, verbose_name='Nota de Verificación realizada')),
                ('revP_ITC', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota Revisar pronto')),
                ('revIM_ITC', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota Revisar de inmediato')),
                ('tipoCli', models.CharField(choices=[('Cliente local', 'Cliente local'), ('Cliente nacional', 'Cliente nacional')], default='Cliente local', max_length=100, verbose_name='Tipo de cliente')),
                ('prenda', models.CharField(choices=[('Vestido', 'Vestido'), ('Pantalón', 'Pantalón'), ('Chaqueta', 'Chaqueta'), ('Blusa/Camisa', 'Blusa/Camisa')], default='Vestido', max_length=100, verbose_name='Tipos de prenda')),
                ('estilCli', models.CharField(choices=[('Clasico', 'Clasico'), ('Deportivo', 'Deportivo'), ('Moderno', 'Moderno'), ('Oficio', 'Oficio'), ('Otro', 'Otro'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=100, verbose_name='Estilo del cliente')),
                ('medPag', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Giro', 'Giro')], default='Efectivo', max_length=100, verbose_name='Medio de pago habitual')),
            ],
            options={
                'verbose_name': 'Detalle Cliente',
                'verbose_name_plural': 'Detalles Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RegUsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomComUsu', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('e_mailUsu', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('passwordUsu', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('conf_passwordUsu', models.CharField(max_length=10, verbose_name='Confirmar Contraseña')),
                ('accept_terms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registrar usuario',
                'verbose_name_plural': 'Registrar Usuarios',
                'ordering': ['id'],
            },
        ),
    ]
