# Generated by Django 3.2.4 on 2021-08-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='todopedido',
            name='DeleteAccount',
        ),
        migrations.RemoveField(
            model_name='todopedido',
            name='DeleteClient',
        ),
        migrations.RemoveField(
            model_name='cronoform',
            name='DeleteAccount',
        ),
        migrations.RemoveField(
            model_name='cronoform',
            name='DeleteClient',
        ),
        migrations.RemoveField(
            model_name='infoclient',
            name='DeleteAccount',
        ),
        migrations.RemoveField(
            model_name='infogeneclient',
            name='DeleteAccount',
        ),
        migrations.RemoveField(
            model_name='infogeneclient',
            name='DeleteClient',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Todopedido',
        ),
    ]
