# Generated by Django 3.2.4 on 2021-08-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210807_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infogeneclient',
            name='DeleteClient',
        ),
        migrations.RemoveField(
            model_name='cronoform',
            name='DeleteClient',
        ),
        migrations.RemoveField(
            model_name='todopedido',
            name='DeleteClient',
        ),
        migrations.DeleteModel(
            name='InfoClient',
        ),
        migrations.DeleteModel(
            name='InfoGeneClient',
        ),
    ]
