# Generated by Django 3.2.4 on 2021-08-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nom_usu',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='security_question',
            field=models.CharField(choices=[('', 'Seleccione una pregunta'), ('Color favorito', 'Color favorito'), ('Comida favorita ', 'Alimento favorito'), ('Mascota de la infancia', 'Mascota de la infancia'), ('Persona admirada', 'Persona admirada'), ('Libro favorito', 'Libro favorito'), ('Canción Favorita', 'Canción favorita')], default='', max_length=30),
        ),
    ]
